using System.Globalization;

namespace Tfx;

internal static class Loc
{
    public static bool IsJapanese { get; } =
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ja", StringComparison.OrdinalIgnoreCase);

    public static string T(string key) => IsJapanese && Japanese.TryGetValue(key, out var value) ? value : key;

    public static string F(string key, params object[] args) =>
        string.Format(CultureInfo.CurrentCulture, T(key), args);

    private static readonly Dictionary<string, string> Japanese = new()
    {
        ["Back (Ctrl+[)"] = "戻る (Ctrl+[)",
        ["Forward (Ctrl+])"] = "進む (Ctrl+])",
        ["Up (Ctrl+Up / Backspace)"] = "上へ (Ctrl+Up / Backspace)",
        ["Open folder"] = "フォルダーを開く",
        ["Pin / unpin current folder"] = "現在のフォルダーをピン留め/解除",
        ["Edit current path (Ctrl+L)"] = "現在のパスを編集 (Ctrl+L)",
        ["Focus search (Ctrl+F)"] = "検索へ移動 (Ctrl+F)",
        ["Switch view mode"] = "表示モード切替",
        ["Toggle hidden files (Ctrl+Shift+.)"] = "隠しファイル表示切替 (Ctrl+Shift+.)",
        ["Open Terminal here (Ctrl+Shift+T)"] = "ここでターミナルを開く (Ctrl+Shift+T)",
        ["Reveal in Explorer"] = "エクスプローラーで表示",
        ["Select all (Ctrl+A)"] = "すべて選択 (Ctrl+A)",
        ["Reload (Ctrl+R)"] = "再読み込み (Ctrl+R)",
        ["Toggle preview"] = "プレビュー切替",
        ["Toggle preview (Ctrl+Shift+P)"] = "プレビュー切替 (Ctrl+Shift+P)",
        ["Toggle split pane (Ctrl+\\)"] = "分割表示切替 (Ctrl+\\)",
        ["Swap left and right panes (Ctrl+Shift+S)"] = "左右ペインを入れ替え (Ctrl+Shift+S)",
        ["Show rendered Markdown / HTML"] = "Markdown / HTML をレンダリング表示",
        ["Show source"] = "ソースを表示",
        ["Show rendered preview"] = "レンダリング表示",
        ["Showing {0} of {1} rows"] = "{1} 行中 {0} 行を表示",
        ["Showing {0} of {1} columns"] = "{1} 列中 {0} 列を表示",
        ["WebView2 runtime is unavailable: {0}"] = "WebView2 ランタイムが利用できません: {0}",
        ["Toggle split pane"] = "分割表示切替",
        ["Columns"] = "列",
        ["Copy current path"] = "現在のパスをコピー",
        ["PINNED"] = "ピン留め",
        ["Pin +"] = "ピン +",
        ["Pin -"] = "ピン -",
        ["Pin"] = "ピン留め",
        ["Unpin"] = "ピン留めを外す",
        ["FOLDERS"] = "フォルダー",
        ["PREVIEW"] = "プレビュー",
        ["Name"] = "名前",
        ["Date modified"] = "更新日時",
        ["Type"] = "種類",
        ["Size"] = "サイズ",
        ["Date created"] = "作成日時",
        ["Owner"] = "所有者",
        ["Attribute"] = "属性",
        ["Open"] = "開く",
        ["Open with..."] = "アプリケーションで開く...",
        ["Open with failed: {0}"] = "アプリケーションで開く処理に失敗しました: {0}",
        ["Cut"] = "切り取り",
        ["Copy"] = "コピー",
        ["Paste"] = "貼り付け",
        ["Compress to Zip"] = "ZIP に圧縮",
        ["Extract Zip"] = "ZIP を展開",
        ["Rename"] = "名前の変更",
        ["Move to Recycle Bin"] = "ごみ箱へ移動",
        ["Delete permanently"] = "完全に削除",
        ["New Folder"] = "新規フォルダー",
        ["New File"] = "新規ファイル",
        ["Folder name"] = "フォルダー名",
        ["File name"] = "ファイル名",
        ["New File.txt"] = "新規ファイル.txt",
        ["Open Terminal here"] = "ここでターミナルを開く",
        ["OK"] = "OK",
        ["Cancel"] = "キャンセル",
        ["Parent folder"] = "親フォルダー",
        ["Directory"] = "ディレクトリ",
        ["File folder"] = "ファイル フォルダー",
        ["File"] = "ファイル",
        ["{0} File"] = "{0} ファイル",
        ["{0}  {1} items"] = "{0}  {1} 個",
        ["{0}  {1} of {2} selected{3}"] = "{0}  {2} 個中 {1} 個を選択{3}",
        ["{0} items selected ({1})"] = "{0} 個を選択 ({1})",
        ["(+{0} more)"] = "(+{0} 個)",
        ["{0}  {1} free of {2}"] = "{0}  空き {1} / {2}",
        ["Folder not found: {0}"] = "フォルダーが見つかりません: {0}",
        ["Invalid path: {0}"] = "無効なパス: {0}",
        ["At least one file column must be visible"] = "少なくとも 1 列は表示してください",
        ["Hidden files visible"] = "隠しファイルを表示",
        ["Hidden files hidden"] = "隠しファイルを非表示",
        ["Copied path: {0}"] = "パスをコピーしました: {0}",
        ["Cut {0} item(s)"] = "{0} 個を切り取りました",
        ["Copied {0} item(s)"] = "{0} 個をコピーしました",
        ["Pasted {0} item(s)"] = "{0} 個を貼り付けました",
        ["Pasted {0}; source remained for: {1}"] = "{0} 個を貼り付けました。元が残ったもの: {1}",
        ["Pasted {0}; failed: {1}"] = "{0} 個を貼り付けました。失敗: {1}",
        ["Source remained for: {0}"] = "元が残ったもの: {0}",
        ["Failed: {0}"] = "失敗: {0}",
        ["Move {0} item(s) to Recycle Bin?"] = "{0} 個をごみ箱へ移動しますか?",
        ["Created {0}"] = "作成しました: {0}",
        ["New folder failed: {0}"] = "新規フォルダー作成に失敗しました: {0}",
        ["New file failed: {0}"] = "新規ファイル作成に失敗しました: {0}",
        ["Invalid name: {0}"] = "無効な名前です: {0}",
        ["Rename failed: {0}"] = "名前の変更に失敗しました: {0}",
        ["Permanently delete \"{0}\"? This cannot be undone."] = "\"{0}\" を完全に削除しますか? この操作は元に戻せません。",
        ["Permanently delete {0} item(s)? This cannot be undone."] = "{0} 個を完全に削除しますか? この操作は元に戻せません。",
        ["Archive"] = "アーカイブ",
        ["Compress failed: {0}"] = "圧縮に失敗しました: {0}",
        ["Select one or more .zip files to extract"] = "展開する .zip ファイルを 1 つ以上選択してください",
        ["Extract failed: {0}"] = "展開に失敗しました: {0}",
        ["Extracted {0} archive(s)"] = "{0} 個のアーカイブを展開しました",
        ["{0} - Shortcut.lnk"] = "{0} - ショートカット.lnk",
        ["Unpinned {0}"] = "ピン留めを解除しました: {0}",
        ["Pinned {0}"] = "ピン留めしました: {0}",
        ["Modified: {0}"] = "更新日時: {0}",
        ["Created: {0}"] = "作成日時: {0}",
        ["Owner: {0}"] = "所有者: {0}",
        ["Attributes: {0}"] = "属性: {0}",
        ["Preview error: {0}"] = "プレビュー エラー: {0}",
        ["PDF preview is unavailable: {0}"] = "PDF プレビューを表示できません: {0}",
        ["Encoding: {0}"] = "エンコード: {0}",
        ["Newline: {0}"] = "改行コード: {0}",
        ["No PDF renderer or thumbnail provider is available."] = "PDF レンダラーまたはサムネイルプロバイダーがありません。",
        ["PDF renderer timed out."] = "PDF レンダラーがタイムアウトしました。",
        ["PDF renderer exited with code {0}."] = "PDF レンダラーが終了コード {0} で終了しました。",
        ["Double-click or press Ctrl+L to edit path"] = "ダブルクリックまたは Ctrl+L でパスを編集",
        ["None"] = "なし",
        ["Mixed (CRLF: {0}, LF: {1}, CR: {2})"] = "混在 (CRLF: {0}, LF: {1}, CR: {2})"
    };
}
